# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv', models.CharField(max_length=50, verbose_name='收件人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('nation', models.CharField(max_length=50, verbose_name='国家')),
                ('province', models.CharField(max_length=50, verbose_name='省区')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('country', models.CharField(max_length=50, verbose_name='县区')),
                ('street', models.CharField(max_length=50, verbose_name='街道')),
                ('intro', models.TextField(verbose_name='详细地址')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
