# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('sale', models.IntegerField(verbose_name='商品销量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('intro', models.TextField(verbose_name='商品描述')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='static/images/goods')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(default='static/images/goodstype/type.jpg', upload_to='static/images/goodstype')),
                ('intro', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='所属商店'),
        ),
    ]
